name: escuelas_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloudinary: ^1.2.0
  dart_jsonwebtoken: ^2.8.2
  envied: ^0.5.2
  logging: ^1.2.0
  mailer: ^6.0.1
  serverpod: 1.2.0-rc.1
  serverpod_auth_server: 1.2.0-rc.1
  yaml_writer: ^1.0.3
  
dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  lints: ^3.0.0
