name: escuelas_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: 1.2.3
  serverpod_auth_client: 1.2.3
  rolemissions:
    path: ../rolemissions
  escuelas_commons:
    path: ../escuelas_commons
